services:
  bot:
    build:
      context: ./bot
    environment:
      CHROME_PATH: /usr/bin/google-chrome-stable
      FFMPEG_PATH: /usr/bin/ffmpeg
    volumes:
      - node_modules:/app/node_modules
      - wwebjs_auth:/app/.wwebjs_auth
    command: /bin/sh -c "rm -f /app/.wwebjs_auth/session/SingletonLock && npm run dev"
    restart: always

volumes:
  node_modules:
  wwebjs_auth: