services:
  bot:
    build:
      context: ./bot
    environment:
      CHROME_PATH: /usr/bin/google-chrome-stable
      FFMPEG_PATH: /usr/bin/ffmpeg
    volumes:
      - ./bot/src:/app/src
      - node_modules:/app/node_modules
      - wwebjs_auth:/app/.wwebjs_auth
    restart: unless-stopped

volumes:
  node_modules:
  wwebjs_auth: